Repository ibexa/content-forms, pull requests merged in 2023-12, with the labels that each got.

#56 IBX-7310: Fixed max file size value for Image Asset
  src/lib/Form/Type/FieldType/ImageAssetFieldType.php
Labels: Bug, QA approved, Ready for review

#55 IBX-6856: Added view variable mime types for ezimage field type
  src/lib/Form/Type/FieldType/ImageAssetFieldType.php
  src/lib/Form/Type/FieldType/ImageFieldType.php
Labels: Feature, Ready for QA

#58 IBX-7020: Fixed redirect after saving and closing
  src/lib/Form/Processor/ContentFormProcessor.php
Labels: Bug, Ready for review
